version: '3.8'

services:
  redis-master1:
    image: redis:6-alpine
    container_name: redis-master1
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "6379:6379"
      - "16379:16379"

    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-master1/data:/data
    command: 
      - "redis-server" 
      - "/usr/local/etc/redis/redis.conf"
      - "--cluster-announce-ip 192.168.1.216" # 宿主机的ip
      - "--cluster-announce-port 6379" # 服务器通讯IP
      - "--cluster-announce-bus-port 16379" #服务器集群通信IP
    networks:
      - redis-cluster
      
  redis-master2:
    image: redis:6-alpine
    container_name: redis-master2
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "6380:6379"
      - "16380:16379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-master2/data:/data
    command:
      - "redis-server" 
      - "/usr/local/etc/redis/redis.conf"
      - "--cluster-announce-ip 192.168.1.216"
      - "--cluster-announce-port 6380"
      - "--cluster-announce-bus-port 16380"
    networks:
      - redis-cluster
      
  redis-master3:
    image: redis:6-alpine
    container_name: redis-master3
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "6381:6379"
      - "16381:16379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-master3/data:/data
    command:
      - "redis-server" 
      - "/usr/local/etc/redis/redis.conf"
      - "--cluster-announce-ip 192.168.1.216"
      - "--cluster-announce-port 6381"
      - "--cluster-announce-bus-port 16381"
    networks:
      - redis-cluster
  
  redis-slave1:
    image: redis:6-alpine
    container_name: redis-slave1
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "6382:6379"
      - "16382:16379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-slave1/data:/data
    command:
      - "redis-server" 
      - "/usr/local/etc/redis/redis.conf"
      - "--cluster-announce-ip 192.168.1.216"
      - "--cluster-announce-port 6382"
      - "--cluster-announce-bus-port 16382"
    networks:
      - redis-cluster         
                        
  redis-slave2:
    image: redis:6-alpine
    container_name: redis-slave2
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "6383:6379"
      - "16383:16379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-slave2/data:/data
    command:
      - "redis-server" 
      - "/usr/local/etc/redis/redis.conf"
      - "--cluster-announce-ip 192.168.1.216"
      - "--cluster-announce-port 6383"
      - "--cluster-announce-bus-port 16383"
    networks:
      - redis-cluster
      
  redis-slave3:
    image: redis:6-alpine
    container_name: redis-slave3
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "6384:6379"
      - "16384:16379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-slave3/data:/data
    command:
      - "redis-server" 
      - "/usr/local/etc/redis/redis.conf"
      - "--cluster-announce-ip 192.168.1.216"
      - "--cluster-announce-port 6384"
      - "--cluster-announce-bus-port 16384"
    networks:
      - redis-cluster

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: always
    ports:
      - '8080:8080'
      - '6371:6371'
    depends_on:
      - redis-master1
      - redis-master2
      - redis-master3
      - redis-slave1
      - redis-slave2
      - redis-slave3
    networks:
      - redis-cluster
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
                                                      
networks:
  redis-cluster:
    driver: bridge
